services:
  # Backend service for development
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ez_ai_agent
      - JWT_SECRET=ez_ai_agent_jwt_secret
      - JWT_EXPIRES_IN=1d
      - LOG_LEVEL=info
      - DB_MAX_RETRIES=10
      - DB_RETRY_INTERVAL=5000
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  # PostgreSQL service
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ez_ai_agent
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
